### ISSUE TITLE
Add in references to packages in Table 1

### ISSUE THREAD

**Issue by geanders** [cjwendt/plos_ten#126]
This may take some LaTeX magic

**Comment by cjwendt** [comment]
Maybe we could add the citation in the "Author" column of the table. I tried, but couldn't work enough LaTex magic. Could you take a look and let me know if you have any success? Would we just use `\cite{}` with the existing bib file?

**Comment by geanders** [comment]
I'd try `\cite{}` then, if that won't work, `\\cite{}`. Sometimes RMarkdown strips off one of the `\` when it processes. If that doesn't work, let me know, and I can take a look.

**Comment by cjwendt** [comment]
`\cite{}` works somewhat, but gives [?].

`\\cite{}` did not work.

I added some refs in the bib for packages mentioned in Table 1 that were not already in the bib. I left my LaTex placeholder citations (using `\cite{}`) for each package in the table. I also tried to cite `biobroom` in the footnote. You should be able to see each [?] in the knitted pdf---Hopefully a quick fix on your end?

**Comment by geanders** [comment]
When you use `\cite`, you don't need the `@`. I think that's causing the ?s. I'll try taking those out.

**Comment by geanders** [comment]
Nope, that didn't do it...

**Comment by geanders** [comment]
I wonder if we just need to pass the TeX file through LaTeX again...

**Comment by geanders** [comment]
I am at a loss on this one. I think it may come down to a combination of factors with how knitr passes everything through the TeX/BibTeX engines, combined with the specialized style sheet that we're using to get it in the PLoS format. I think we have two options at this point: we could either take the citations to the packages out of the table, or we could add in the numbers by hand (hardcode them). Do you have any preference one way or the other? I'd be fine with either.

**Comment by cjwendt** [comment]
We decided to take the references out of Table 1 for now. Many (if not all) of the packages are cited elsewhere.
