### ISSUE TITLE
Add more to abstract?

### ISSUE THREAD

**Issue by cjwendt** [cjwendt/plos_ten#130]
Did we decide to expand last few sentences of the abstract? If so, could you write some ideas in so I can get a sense for how you'd like to go about that?

**Comment by cjwendt** [comment]
To clarify, I'm referring to the part where we are adding a brief summary of the Rules.

**Comment by geanders** [comment]
Yes, let's expand some. We can go up to 300 words in the abstract, and we're currently at 117. I suggest we add up to three sentences after "Rules 3 through 8 will help you navigate packages' profiles and investigate development processes, so you can assess their quality and merit," to add some more details on what we present in these rules. Something along the lines of "These rules begin by expand on how you can assess how a package is shared and determine the extent of help resources for the package. They continue with tips on exploring the package's popularity and evidence of peer use and review, as well as advice on tracking the package's development process."
