### ISSUE TITLE
??? now replacing some references in text

### ISSUE THREAD

**Issue by cjwendt** [cjwendt/plos_ten#134]
pages 7, 10, 11, 15

**Comment by cjwendt** [comment]
@geanders Did you remove these references when editing the .bib?

**Comment by geanders** [comment]
There were some duplicates, where we had several entries that were essentially the same paper or resource. For example, I think we had three different bibtex entries that were all referencing the `testthat` package. I tried to make sure I replaced with the relevant key when possible, but may have missed some. I can take a look at this later today and fix those ??? sections.

**Comment by cjwendt** [comment]
Okay, thanks for catching those! I think we had 100 references before, and now we have 97.
