### ISSUE TITLE
Add references when we are linking to a website

### ISSUE THREAD

**Issue by geanders** [cjwendt/plos_ten#51]
I love that we have embedded links. The format of the journal doesn't make it obvious that we can click on them, though. I suggest that we also use citations each time we do this. You could try these styles for making BibTex citations for those: 

```
@misc{WinNT,
  title = {{MS Windows NT} Kernel Description},
  howpublished = {\url{http://web.archive.org/web/20080207010024/http://www.808multimedia.com/winnt/kernel.htm}},
  note = {Accessed: 2010-09-30}
}
```

or

```
@manual{senn2009,
      title  = "Using {\LaTeX} for Your Thesis",
      author = "Mark Senn",
      url    = "http://engineering.purdue.edu/~mark/puthesis",
      year   = "2009 (accessed February 3, 2014)"
    }
```

See if it looks like one looks more appropriate in the citations that the other. We could also look at how other PLOS journal articles cited websites, for the articles we found with their manuscript code on GitHub.

**Comment by cjwendt** [comment]
We decided to not do this-- at least for now.
